phrase:
  project_id: efd34b09f60867879304c3c810b480a4
  push:
    sources:
      - file: ./<locale_code>.json
        params:
          file_format: simple_json
          locale_code: en-US
          autotranslate: false
  pull:
    targets:
      - file: ./<locale_code>.json
        params:
          file_format: simple_json
